# Generated by Django 3.2.7 on 2021-11-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsored',
            name='complete',
        ),
    ]
