# Generated by Django 3.2.7 on 2021-09-27 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('Comedy', 'Comedy'), ('Commentary', 'Commentary'), ('Educational', 'Educational'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Interview', 'Interview'), ('Music', 'Music'), ('ProductReview', 'ProductReview'), ('Q&A', 'Q&A'), ('Reaction', 'Reaction'), ('Sport', 'Sport')], max_length=50)),
                ('profileImg', models.ImageField(upload_to='media/profileImg/influencer')),
                ('pancard', models.CharField(max_length=12, null=True)),
                ('mode_of_transaction', models.CharField(choices=[('1', 'NetBanking'), ('2', 'Card'), ('3', 'UPI'), ('4', 'Other')], max_length=25)),
                ('bank_name', models.CharField(max_length=25, null=True)),
                ('IFSC_code', models.CharField(max_length=15, null=True)),
                ('account_no', models.CharField(max_length=15, null=True)),
                ('phone_no', models.CharField(max_length=13)),
                ('address', models.TextField(max_length=300)),
                ('website_link', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('instagram_name', models.CharField(max_length=30)),
                ('instagram', models.URLField(null=True)),
                ('follower', models.IntegerField()),
                ('twitter', models.URLField(null=True)),
                ('youtube_name', models.CharField(max_length=30)),
                ('youtube', models.URLField(null=True)),
                ('subscriber', models.IntegerField()),
                ('other_link', models.URLField(null=True)),
                ('is_verified', models.BooleanField(null=True)),
                ('influencer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=500, null=True)),
                ('field', models.CharField(choices=[('Comedy', 'Comedy'), ('Commentary', 'Commentary'), ('Educational', 'Educational'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Interview', 'Interview'), ('Music', 'Music'), ('ProductReview', 'ProductReview'), ('Q&A', 'Q&A'), ('Reaction', 'Reaction'), ('Sport', 'Sport')], max_length=50)),
                ('post_img', models.ImageField(upload_to='media/profileImg/influencer')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.influencer')),
            ],
        ),
        migrations.CreateModel(
            name='Posted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_link', models.URLField()),
                ('is_accepted', models.BooleanField()),
                ('comment', models.CharField(max_length=300)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.influencer')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('Comedy', 'Comedy'), ('Commentary', 'Commentary'), ('Educational', 'Educational'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Interview', 'Interview'), ('Music', 'Music'), ('ProductReview', 'ProductReview'), ('Q&A', 'Q&A'), ('Reaction', 'Reaction'), ('Sport', 'Sport')], max_length=50)),
                ('profile_img', models.ImageField(upload_to='media/profileImg/sponsor')),
                ('pancard', models.CharField(max_length=12, null=True)),
                ('cin_no', models.CharField(max_length=21, null=True)),
                ('mode_of_transaction', models.CharField(choices=[('1', 'NetBanking'), ('2', 'Card'), ('3', 'UPI'), ('4', 'Other')], max_length=25)),
                ('bank_name', models.CharField(max_length=25, null=True)),
                ('IFSC_code', models.CharField(max_length=15, null=True)),
                ('account_no', models.CharField(max_length=15, null=True)),
                ('phone_no', models.CharField(max_length=13)),
                ('address', models.TextField(max_length=300)),
                ('website_link', models.URLField(null=True)),
                ('facebook', models.URLField(null=True)),
                ('instagram', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('other_link', models.URLField(null=True)),
                ('is_verified', models.BooleanField(null=True)),
                ('sponsor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_sponsorship', models.CharField(choices=[], max_length=50)),
                ('transaction_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField(null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.influencer')),
                ('posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.posted')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sponsor')),
            ],
        ),
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
