# Generated by Django 3.2.7 on 2021-09-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='address',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='influencer',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
