# Generated by Django 3.2.7 on 2021-11-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_content_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
