# Generated by Django 3.2.7 on 2021-09-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210929_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='instagram_name',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='website_link',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='youtube_name',
        ),
    ]
