# Generated by Django 3.2.7 on 2021-11-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_sponsored_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsored',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='sponsored',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
