# Generated by Django 3.2.7 on 2021-10-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210929_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='other_link',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='influencer',
            name='field',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Commentary', 'Commentary'), ('Educational', 'Educational'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Interview', 'Interview'), ('Music', 'Music'), ('ProductReview', 'ProductReview'), ('Q&A', 'Q&A'), ('Reaction', 'Reaction'), ('Sport', 'Sport'), ('Travel', 'Travel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='influencerpost',
            name='field',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Commentary', 'Commentary'), ('Educational', 'Educational'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Interview', 'Interview'), ('Music', 'Music'), ('ProductReview', 'ProductReview'), ('Q&A', 'Q&A'), ('Reaction', 'Reaction'), ('Sport', 'Sport'), ('Travel', 'Travel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='field',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Commentary', 'Commentary'), ('Educational', 'Educational'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Gaming', 'Gaming'), ('Interview', 'Interview'), ('Music', 'Music'), ('ProductReview', 'ProductReview'), ('Q&A', 'Q&A'), ('Reaction', 'Reaction'), ('Sport', 'Sport'), ('Travel', 'Travel')], max_length=50),
        ),
        migrations.CreateModel(
            name='InfSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(max_length=100)),
                ('followers', models.CharField(max_length=30, null=True)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.influencer')),
            ],
        ),
    ]
