# Generated by Django 3.2.7 on 2021-11-09 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20211109_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsored',
            name='posted',
        ),
        migrations.AlterField(
            model_name='sponsored',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
