# Generated by Django 3.2.7 on 2021-10-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211003_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='infsocialmedia',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='infsocialmedia',
            name='social_media',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
