# Generated by Django 3.2.7 on 2021-11-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211109_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_link', models.URLField()),
                ('is_accepted', models.BooleanField()),
                ('comment', models.CharField(max_length=300)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.influencer')),
            ],
        ),
    ]
