# Generated by Django 3.2.7 on 2021-10-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211004_1138'),
        ('app', '0005_auto_20211003_2245'),
    ]

    operations = [
    ]
