# Generated by Django 3.2.7 on 2021-11-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sponsored_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='IFSC_code',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='mode_of_transaction',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
