# Generated by Django 3.2.7 on 2021-10-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_influencerpost_adfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerpost',
            name='adfield',
            field=models.CharField(choices=[('Facebook Post', 'Facebook Post'), ('Facebook Story + Swipe Up', 'Facebook Story + Swipe Up'), ('Instgram Post', 'Instgram Post'), ('Instgram Reels', 'Instgram Reels'), ('Instgram Story + Swipe Up', 'Instgram Story + Swipe Up'), ('Tiktok Video', 'Tiktok Video'), ('YouTube Shorts + Swipe Up', 'YouTube Shorts + Swipe Up'), ('YouTube Video', 'YouTube Video')], max_length=50, null=True),
        ),
    ]
