# Generated by Django 3.2.7 on 2021-10-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_influencerpost_adfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerpost',
            name='slug',
        ),
    ]
