# Generated by Django 3.2.7 on 2021-10-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_infsavepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infsavepost',
            old_name='influencer',
            new_name='who_saved',
        ),
    ]
