# Generated by Django 3.2.7 on 2021-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_influencer_infsavepost_who_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerpost',
            name='adfield',
            field=models.CharField(choices=[('Facebook Post', 'Facebook Post'), ('Facebook Story + Swipe Up', 'Facebook Story + Swipe Up'), ('Instagram Post', 'Instagram Post'), ('Instagram Reels', 'Instagram Reels'), ('Instagram Story + Swipe Up', 'Instagram Story + Swipe Up'), ('Tiktok Video', 'Tiktok Video'), ('YouTube Shorts + Swipe Up', 'YouTube Shorts + Swipe Up'), ('YouTube Video', 'YouTube Video')], max_length=50, null=True),
        ),
    ]
